# Default values for event-handler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#
# Plugin specific options
#
teleport:
  address: "test.example.com:443"
  identitySecretName: "test-id"
  identitySecretPath: "auth_id"

eventHandler:
  storagePath: "/var/lib/teleport/plugins/event-handler/storage"
  timeout: "10s"
  batch: 20

fluentd:
  url: "https://fluentd.fluentd.svc.cluster.local/events.log"
  sessionUrl: "https://fluentd.fluentd.svc.cluster.local/session.log"
  certificate:
    secretName: "test"
    caPath: "ca.crt"
    certPath: "client.crt"
    keyPath: "client.key"

persistentVolumeClaim:
  enabled: false
  size: 1Gi
  storageClassName: ""
  existingClaim: ""
  volumeName: "storage"

#
# Deployment
#
image:
  repository: public.ecr.aws/gravitational/teleport-plugin-event-handler
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  runAsNonRoot: false
  seccompProfile:
    type: RuntimeDefault
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 500m
    memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}

volumes: []
  # - name: storage
  #   persistentVolumeClaim:
  #     claimName: teleport-plugin-event-handler

volumeMounts: []
  # - name: storage
  #   mountPath: "/var/lib/teleport/plugins/event-handler/storage"
